/**
 * @description Enforces the React starter's authoring conventions: every source declaration has
 * a useful JSDoc `@description`, and non-static class methods are ordered private-first and then
 * alphabetically. Import grouping is intentionally handled by `sort-imports.ts`, because import
 * labels are a repository convention rather than a TypeScript semantic rule.
 */

// Node Libraries
import { globSync, readFileSync } from 'node:fs';
import { relative, resolve } from 'node:path';
import process from 'node:process';

// TypeScript
import ts from 'typescript';

/**
 * @description Source paths covered by the convention ratchet. Generated declarations and
 * Storybook fixtures are excluded below because they are not authored application APIs.
 */
const RATCHETED_PATHS: readonly string[] = ['src/**/*.ts', 'src/**/*.tsx'];

/**
 * @description Files generated by tooling or supplied by the Vite type environment rather than
 * authored as application declarations.
 */
const GENERATED_FILES: readonly string[] = [
  'src/app/types/auto-imports.d.ts',
  'src/auto-imports.d.ts',
  'src/vite-env.d.ts',
];

/**
 * @description One convention violation, ready to print with a stable file and line reference.
 */
interface IViolation {
  file: string;
  line: number;
  rule: string;
  message: string;
}

/**
 * @description Returns the source-file kind needed for JSX-aware TypeScript parsing.
 *
 * @param file The file path being parsed.
 */
function scriptKindFor(file: string): ts.ScriptKind {
  return file.endsWith('.tsx') ? ts.ScriptKind.TSX : ts.ScriptKind.TS;
}

/**
 * @description Reads a class member name, returning an empty string for computed names that
 * cannot be ordered safely.
 *
 * @param member The class member to inspect.
 */
function memberName(member: ts.ClassElement): string {
  return member.name !== undefined && ts.isIdentifier(member.name) ? member.name.text : '';
}

/**
 * @description Checks whether a declaration has a JSDoc block containing the explicit
 * `@description` tag required by the repository convention.
 *
 * @param node The declaration to inspect.
 * @param text The complete source text.
 */
function hasDescription(node: ts.Node, text: string): boolean {
  const ranges = ts.getLeadingCommentRanges(text, node.pos) ?? [];

  return ranges.some((range) => {
    const comment = text.slice(range.pos, range.end);

    return comment.startsWith('/**') && comment.includes('@description');
  });
}

/**
 * @description Reports declarations that do not explain their purpose with a JSDoc description.
 * Constructors are omitted because their class documentation already describes the type.
 *
 * @param source The parsed TypeScript source file.
 * @param text The complete source text.
 * @param file The relative path used in diagnostics.
 */
function checkDescriptions(source: ts.SourceFile, text: string, file: string): IViolation[] {
  const violations: IViolation[] = [];

  const report = (node: ts.Node, what: string): void => {
    if (hasDescription(node, text)) {
      return;
    }

    violations.push({
      file,
      line: source.getLineAndCharacterOfPosition(node.getStart(source)).line + 1,
      rule: 'require-description',
      message: `${what} has no JSDoc @description`,
    });
  };

  const visit = (node: ts.Node): void => {
    if (ts.isClassDeclaration(node) && node.name) {
      report(node, `class ${node.name.text}`);
    }

    if (ts.isInterfaceDeclaration(node)) {
      report(node, `interface ${node.name.text}`);
    }

    if (ts.isTypeAliasDeclaration(node)) {
      report(node, `type ${node.name.text}`);
    }

    if (ts.isFunctionDeclaration(node) && node.name) {
      report(node, `function ${node.name.text}`);
    }

    if (ts.isMethodDeclaration(node) && node.name?.getText(source) !== 'constructor') {
      report(node, `method ${memberName(node)}`);
    }

    if (ts.isVariableStatement(node) && node.parent === source) {
      for (const declaration of node.declarationList.declarations) {
        report(node, `module declaration ${declaration.name.getText(source)}`);
      }
    }

    ts.forEachChild(node, visit);
  };

  ts.forEachChild(source, visit);

  return violations;
}

/**
 * @description Reports non-static class methods that are not private-first and alphabetical.
 * Static React lifecycle methods are ignored because their framework-defined placement is more
 * readable than forcing them into an authoring-only alphabetical order.
 *
 * @param source The parsed TypeScript source file.
 * @param file The relative path used in diagnostics.
 */
function checkMemberOrder(source: ts.SourceFile, file: string): IViolation[] {
  const violations: IViolation[] = [];

  const visit = (node: ts.Node): void => {
    if (ts.isClassDeclaration(node)) {
      const methods = node.members.filter(
        (member): member is ts.MethodDeclaration =>
          ts.isMethodDeclaration(member) &&
          !(member.modifiers ?? []).some(
            (modifier) => modifier.kind === ts.SyntaxKind.StaticKeyword,
          ),
      );
      const isPrivate = (member: ts.MethodDeclaration): boolean =>
        (member.modifiers ?? []).some((modifier) => modifier.kind === ts.SyntaxKind.PrivateKeyword);
      const expected = [
        ...methods.filter(isPrivate).sort((a, b) => memberName(a).localeCompare(memberName(b))),
        ...methods
          .filter((member) => !isPrivate(member))
          .sort((a, b) => memberName(a).localeCompare(memberName(b))),
      ];

      for (const [index, method] of methods.entries()) {
        const expectedMethod = expected[index];

        if (method === expectedMethod) {
          continue;
        }

        violations.push({
          file,
          line: source.getLineAndCharacterOfPosition(method.getStart(source)).line + 1,
          rule: 'member-order',
          message: `${memberName(method)} is out of order; expected ${expectedMethod ? memberName(expectedMethod) : 'nothing'}`,
        });
      }
    }

    ts.forEachChild(node, visit);
  };

  ts.forEachChild(source, visit);

  return violations;
}

/**
 * @description Entry point. Every reported violation is actionable and causes a non-zero exit so
 * CI cannot silently accumulate undocumented declarations or unreadable class ordering.
 */
function main(): void {
  const files = RATCHETED_PATHS.flatMap((pattern) => globSync(pattern))
    .filter((file) => !file.includes('.stories.') && !GENERATED_FILES.includes(file))
    .sort();
  const violations: IViolation[] = [];

  for (const file of files) {
    const text = readFileSync(resolve(file), 'utf8');
    const source = ts.createSourceFile(
      file,
      text,
      ts.ScriptTarget.Latest,
      true,
      scriptKindFor(file),
    );
    const relativePath = relative(process.cwd(), resolve(file));

    violations.push(
      ...checkDescriptions(source, text, relativePath),
      ...checkMemberOrder(source, relativePath),
    );
  }

  if (violations.length === 0) {
    return;
  }

  const lines = violations.map(
    (violation) => `  ${violation.file}:${violation.line}  ${violation.rule}  ${violation.message}`,
  );

  process.stderr.write(
    `Convention check failed with ${violations.length} violation(s):\n${lines.join('\n')}\n\n` +
      'See CLAUDE.md "Code conventions" for the required JSDoc and member-order rules.\n',
  );
  process.exit(1);
}

main();
